// Short-lived store for a TFA secret freshly generated by `/api/auth/2fa/generate`,
// looked up by `/api/auth/2fa/enable` so the client cannot substitute its own
// secret (audit finding H2).
//
// Keyed by the session id from the existing `gs_session` cookie — no separate
// cookie. Single-process Fly machine assumption, same as the other auth stores.

export const PENDING_TFA_TTL_MS = 10 * 60_000;

export type PendingTfaData = {
  secret: string;
  expiresAt: number;
};

export type PendingTfaStoreConfig = {
  now?: () => number;
};

export type PendingTfaStore = {
  create: (sessionId: string, data: PendingTfaData) => void;
  get: (sessionId: string) => PendingTfaData | undefined;
  delete: (sessionId: string) => void;
  cleanupExpired: () => void;
  size: () => number;
};

export function createPendingTfaStore(config: PendingTfaStoreConfig = {}): PendingTfaStore {
  const now = config.now ?? Date.now;
  const entries = new Map<string, PendingTfaData>();

  return {
    create(sessionId, data) {
      entries.set(sessionId, data);
    },

    get(sessionId) {
      const entry = entries.get(sessionId);
      if (!entry) return undefined;
      if (entry.expiresAt <= now()) {
        entries.delete(sessionId);
        return undefined;
      }
      return entry;
    },

    delete(sessionId) {
      entries.delete(sessionId);
    },

    cleanupExpired() {
      const t = now();
      for (const [id, entry] of entries) {
        if (entry.expiresAt <= t) entries.delete(id);
      }
    },

    size() {
      return entries.size;
    },
  };
}
