"""Multi-year resting-HR (RHR) trajectory characterisation + confounder decomposition.

Producer-mode analysis. Implements the LOCKED design in
`driver_ledger.md` (section 4 model form, section 3 discriminator,
section 5 collinearity/measurement limits). This is EXPLORATORY estimation,
NOT a pre-registered falsification test.

Part A: descriptive RHR trajectory (Layer-1, no causal marks).
Part B: literature-gated confounder decomposition, LC residual, sensitivity
across two deconditioning curves (literature exponential + Garmin VO2Max decay).

REVISED 2026-07-02 per skeptical review
`../../reviews/longrun-rhr-decomposition-2026-07-02.md`. This revision:
  1. corrects the post-2023 residual-slope CI: a PROPER block bootstrap OF THE
     RESIDUAL SLOPE ITSELF (paired (t, y) blocks, Theil-Sen per resample),
     replacing the mislabelled analytic Theil-Sen interval that ignored the
     residual's lag-1 autocorrelation (~0.94).
  2. adds a leave-one-year-out (LOYO) table for the post-2023 residual slope.
  3. adds a weight-coefficient sensitivity and discloses the 523-day post-2023
     weigh-in gap under the leverage window.
  4. adds a slow-continuing / never-plateauing deconditioning sensitivity
     (plateau at yr2/yr3/yr4 and a linear-forever ramp), the empirical
     circularity defeater.
  5. folds in the resting-HR aging bound (~0 to ~0.3 bpm/yr upper) from
     `../../literature/reviews/resting_hr_aging_magnitude_review.md`; the 0.5
     bpm/yr aging cap OVER-removes aging, so the residual is conservative.

"stress" everywhere = Garmin HRV-derived stress score (GSS), NOT mental stress.

Run:  python decomposition.py
Outputs numbers to stdout. findings.md is generated by make_findings.py from a
fresh run of this module (import-safe: all compute lives in callable functions).

Data paths are local; no PII beyond the data path is emitted.
Author: Claude (Opus 4.8) producer-mode analysis, for the participant-researcher (repo owner).
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import least_squares
from scipy.stats import theilslopes

SEED = 20260702
rng = np.random.default_rng(SEED)
N_WEIGHIN_RAW = None  # set in load_weight_series

# ---------------------------------------------------------------------------
# Paths + locked constants
# ---------------------------------------------------------------------------
DATA_DIR = Path(r"C:\Users\Gebruiker\Documents\gevoelscore-data")
CSV = DATA_DIR / "unified" / "per_day_master.csv"
BIO = (
    DATA_DIR
    / "garmin data"
    / "DI_CONNECT"
    / "DI-Connect-Wellness"
    / "97794221_userBioMetrics.json"
)

CESSATION = pd.Timestamp("2022-03-17")   # last real training run
LC_ONSET = pd.Timestamp("2022-04-04")
BIRTH_YEAR = 1981
ATHLETE_BASELINE_KG = 74.0
ANCHOR_2026_KG = 89.0                     # participant-reported "current"
ANCHOR_2026_DATE = pd.Timestamp("2026-05-15")

# literature priors (from the reviews)
LIT_DECOND_BPM_LO, LIT_DECOND_BPM_HI = 5.0, 12.0   # deconditioning RHR-up range
CITALOPRAM_PRIOR_BPM = -8.0                          # DOWN, masks LC elevation
SEASONAL_PRIOR_BPM = 2.0                             # ~2 bpm peak-to-trough
TAU_GRID_MONTHS = [3.0, 4.0, 6.0]                    # literature plateau ~year 1
# aging bound folded in from resting_hr_aging_magnitude_review.md:
# resting-HR aging is ~0 to at most ~0.3 bpm/yr (central near zero or negative).
AGING_UPPER_BOUND_BPM_YR = 0.3
AGING_CAP_BPM_YR = 0.5   # model cap; OVER-removes aging vs the 0.3 lit upper bound

BLOCK_LEN = 10          # block-bootstrap block length (days), lit review says 7-14
BLOCK_LEN_GRID = [10, 20, 30, 45]  # residual-slope bootstrap block grid
N_BOOT = 2000

POST_2023 = pd.Timestamp("2024-01-01")   # start of the post-2023 leverage window

YEAR_SEGMENTS = [
    ("pre_LC", None, pd.Timestamp("2022-03-20")),
    ("2022", pd.Timestamp("2022-03-21"), pd.Timestamp("2022-12-31")),
    ("2023", pd.Timestamp("2023-01-01"), pd.Timestamp("2023-12-31")),
    ("2024", pd.Timestamp("2024-01-01"), pd.Timestamp("2024-12-31")),
    ("2025", pd.Timestamp("2025-01-01"), pd.Timestamp("2025-12-31")),
    ("2026", pd.Timestamp("2026-01-01"), None),
]


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------
def load_master():
    df = pd.read_csv(
        CSV,
        usecols=[
            "date", "resting_hr", "stress_mean_sleep", "bb_highest",
            "dose_plasma_mg", "in_citalopram_traject", "lc_phase",
        ],
    )
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").reset_index(drop=True)
    return df


def load_weight_series():
    """56 nested weigh-ins (grams) + 2026 participant anchor. Returns kg by date.
    Also records the largest weigh-in gap (523 days, 2023-09 to 2025-02)."""
    raw = json.loads(BIO.read_text())
    rows = []
    for e in raw:
        w = e.get("weight")
        if isinstance(w, dict) and w.get("weight") is not None:
            d = pd.Timestamp(e["metaData"]["calendarDate"][:10])
            rows.append((d, w["weight"] / 1000.0))
    wt = pd.DataFrame(rows, columns=["date", "weight_kg"]).sort_values("date")
    global N_WEIGHIN_RAW
    N_WEIGHIN_RAW = len(wt)  # raw weigh-in records (56 per ledger)
    wt = wt.groupby("date", as_index=False)["weight_kg"].mean()  # dedup same-day
    # largest gap in the REAL weigh-in series (before appending the 2026 anchor)
    gaps = wt["date"].diff().dt.days
    gi = int(gaps.idxmax())
    global WEIGH_GAP_DAYS, WEIGH_GAP_FROM, WEIGH_GAP_TO
    WEIGH_GAP_DAYS = int(gaps.max())
    WEIGH_GAP_FROM = wt.loc[gi - 1, "date"].date()
    WEIGH_GAP_TO = wt.loc[gi, "date"].date()
    # append participant-reported 2026 anchor
    wt = pd.concat(
        [wt, pd.DataFrame({"date": [ANCHOR_2026_DATE], "weight_kg": [ANCHOR_2026_KG]})],
        ignore_index=True,
    ).sort_values("date").reset_index(drop=True)
    return wt


def load_vo2_series():
    raw = json.loads(BIO.read_text())
    rows = []
    for e in raw:
        v = e.get("vo2MaxRunning")
        if v is not None:
            d = pd.Timestamp(e["metaData"]["calendarDate"][:10])
            rows.append((d, float(v)))
    vo = pd.DataFrame(rows, columns=["date", "vo2"]).sort_values("date")
    vo = vo.groupby("date", as_index=False)["vo2"].max()  # dedup same-day
    return vo


# ---------------------------------------------------------------------------
# PART A helpers
# ---------------------------------------------------------------------------
def robust_slope_per_year(dates, values):
    """Theil-Sen slope in bpm/year. Returns (slope, lo, hi) 95%."""
    mask = ~np.isnan(values)
    d = pd.to_datetime(dates[mask])
    v = values[mask]
    if len(v) < 5:
        return np.nan, np.nan, np.nan
    t_years = (d - d.min()).days / 365.25
    slope, intercept, lo, hi = theilslopes(v, t_years, alpha=0.95)
    return slope, lo, hi


def window_slope_raw(df, lo, hi):
    """Raw-daily Theil-Sen slope over a date window."""
    m = (df["date"] >= lo) & (df["date"] <= hi)
    sub = df[m]
    return robust_slope_per_year(
        sub["date"].values.astype("datetime64[ns]"),
        sub["resting_hr"].values.astype(float),
    ) + (int(sub["resting_hr"].notna().sum()),)


def rolling_median_slope(df, lo, hi):
    """28-day centred rolling-median trajectory slope (sidesteps integer-tie
    degeneracy of raw-daily Theil-Sen; reviewer fix 5b)."""
    s = df.set_index("date")["resting_hr"].asfreq("D")
    roll = s.rolling(28, center=True, min_periods=10).median()
    sub = roll.loc[lo:hi].dropna()
    t = (sub.index - sub.index.min()).days / 365.25
    sl, ic, cl, ch = theilslopes(sub.values, t, 0.95)
    return sl, cl, ch, len(sub)


def part_a(df):
    print("\n" + "=" * 70)
    print("PART A - DESCRIPTIVE TRAJECTORY (Layer-1, no causal marks)")
    print("=" * 70)

    n_cov = int(df["resting_hr"].notna().sum())
    cal0, cal1 = df["date"].min().date(), df["date"].max().date()
    last_rhr = df.loc[df["resting_hr"].notna(), "date"].max().date()
    print(f"\n[A1] RHR coverage: {n_cov} non-null resting_hr days.")
    print(f"     Master calendar span {cal0} to {cal1} ({len(df)} rows; "
          f"{len(df) - n_cov} rows missing RHR).")
    print(f"     Last non-null RHR date: {last_rhr} "
          f"(final calendar rows are RHR-null).")

    # robust smoothed trajectory: 28-day centred rolling median on a daily grid
    s = df.set_index("date")["resting_hr"].asfreq("D")
    roll = s.rolling(28, center=True, min_periods=10).median()
    print("     Smoothed trajectory = 28-day centred rolling median.")
    print("     Rolling-median value at selected anchors (bpm):")
    for label, dt in [
        ("2021-10 (pre-LC)", "2021-10-15"),
        ("2022-06 (early LC)", "2022-06-15"),
        ("2023-06", "2023-06-15"),
        ("2024-06", "2024-06-15"),
        ("2025-06", "2025-06-15"),
        ("2026-05", "2026-05-15"),
    ]:
        try:
            val = roll.loc[pd.Timestamp(dt)]
        except KeyError:
            val = np.nan
        print(f"       {label:22s}: {val:.1f}")

    # A2: era/year segmented median + robust slope
    print("\n[A2] Era/year robust central tendency + Theil-Sen slope")
    print(f"     {'segment':8s} {'n':>4s} {'median':>7s} "
          f"{'slope_bpm/yr':>13s} {'95%CI':>18s}")
    seg_slopes = {}
    for name, lo, hi in YEAR_SEGMENTS:
        m = pd.Series(True, index=df.index)
        if lo is not None:
            m &= df["date"] >= lo
        if hi is not None:
            m &= df["date"] <= hi
        sub = df[m]
        med = sub["resting_hr"].median()
        sl, cl, ch = robust_slope_per_year(
            sub["date"].values.astype("datetime64[ns]"),
            sub["resting_hr"].values.astype(float),
        )
        seg_slopes[name] = (sl, cl, ch)
        n = int(sub["resting_hr"].notna().sum())
        print(f"     {name:8s} {n:4d} {med:7.1f} {sl:13.2f} "
              f"[{cl:6.2f}, {ch:6.2f}]")

    # A3: plateau check - early-LC vs recent slope, WITH window-sensitivity
    print("\n[A3] Plateau check (front-loading + flattening)")
    windows = [
        ("early-LC 2022-2023", pd.Timestamp("2022-03-21"), pd.Timestamp("2023-12-31")),
        ("recent 2025-2026", pd.Timestamp("2025-01-01"), df["date"].max()),
        ("mid 2023-2024", pd.Timestamp("2023-01-01"), pd.Timestamp("2024-12-31")),
        ("2024-2026", pd.Timestamp("2024-01-01"), df["date"].max()),
    ]
    win_res = {}
    for tag, lo, hi in windows:
        sl, cl, ch, n = window_slope_raw(df, lo, hi)
        win_res[tag] = (sl, cl, ch, n)
        print(f"     raw    {tag:20s} n={n:4d}  slope={sl:6.2f} bpm/yr "
              f"[{cl:.2f}, {ch:.2f}]")
    # 28d rolling-median trajectory slope as the tie-robust discriminator
    print("     28d rolling-median trajectory slopes (tie-robust discriminator):")
    roll_res = {}
    for tag, lo, hi in windows[:3]:
        sl, cl, ch, n = rolling_median_slope(df, lo, hi)
        roll_res[tag] = (sl, cl, ch, n)
        print(f"     rollmed {tag:20s} n={n:4d}  slope={sl:6.2f} bpm/yr "
              f"[{cl:.2f}, {ch:.2f}]")

    early = win_res["early-LC 2022-2023"][:3]
    recent = win_res["recent 2025-2026"][:3]
    y26 = seg_slopes["2026"]
    print(f"     2026-only slope: {y26[0]:.2f} bpm/yr [{y26[1]:.2f}, {y26[2]:.2f}]")
    recent_flat = recent[1] <= 0 <= recent[2]
    print(f"     Recent slope CI includes zero (indistinguishable from flat)? "
          f"{recent_flat}")
    print(f"     Early-LC slope > recent slope (front-loaded)? "
          f"{early[0] > recent[0]}")
    print(f"     Mid 2023-2024 window is flat (a flat window sits inside the "
          f"record): slope {win_res['mid 2023-2024'][0]:.2f}")

    # A4: triad year-medians for context
    print("\n[A4] Triad year-medians (context; stress=Garmin GSS)")
    print(f"     {'segment':8s} {'RHR':>6s} {'stress_sleep':>13s} {'bb_highest':>11s}")
    triad = {}
    for name, lo, hi in YEAR_SEGMENTS:
        m = pd.Series(True, index=df.index)
        if lo is not None:
            m &= df["date"] >= lo
        if hi is not None:
            m &= df["date"] <= hi
        sub = df[m]
        triad[name] = (sub["resting_hr"].median(),
                       sub["stress_mean_sleep"].median(),
                       sub["bb_highest"].median())
        print(f"     {name:8s} {triad[name][0]:6.1f} "
              f"{triad[name][1]:13.1f} "
              f"{triad[name][2]:11.1f}")

    return {"coverage": n_cov, "last_rhr": last_rhr, "cal0": cal0, "cal1": cal1,
            "n_rows": len(df), "seg_slopes": seg_slopes,
            "early": early, "recent": recent, "recent_flat": recent_flat,
            "win_res": win_res, "roll_res": roll_res, "triad": triad}


# ---------------------------------------------------------------------------
# PART B - regressors
# ---------------------------------------------------------------------------
def build_daily_frame(df, wt, vo):
    """Daily grid over the RHR-observed span with all regressors."""
    d = df[df["resting_hr"].notna()].copy()
    d = d[["date", "resting_hr", "dose_plasma_mg"]].reset_index(drop=True)

    t0 = CESSATION
    # time since cessation in years (clamped at 0 before cessation)
    dt_years = (d["date"] - t0).dt.days / 365.25
    d["t_cess"] = dt_years.clip(lower=0.0)
    d["post_cess"] = (d["date"] >= t0).astype(float)

    # aging: years since start of record
    d["age_years"] = (d["date"] - d["date"].min()).dt.days / 365.25

    # seasonal phase (day-of-year)
    doy = d["date"].dt.dayofyear
    d["sin"] = np.sin(2 * np.pi * doy / 365.25)
    d["cos"] = np.cos(2 * np.pi * doy / 365.25)

    # citalopram plasma (mg)
    d["dose"] = d["dose_plasma_mg"].fillna(0.0)

    # weight interpolated to daily (linear), carry-forward outside the hull
    wser = wt.set_index("date")["weight_kg"]
    grid = pd.Series(index=pd.DatetimeIndex(d["date"]), dtype=float)
    combined = pd.concat([wser, grid[~grid.index.isin(wser.index)]]).sort_index()
    combined = combined.interpolate(method="time", limit_direction="both")
    d["weight_kg"] = combined.reindex(pd.DatetimeIndex(d["date"])).values

    # Garmin VO2Max mapped to RHR-up contribution (secondary decond curve).
    vser = vo.set_index("date")["vo2"]
    vgrid = pd.concat([vser, grid[~grid.index.isin(vser.index)]]).sort_index()
    vgrid = vgrid.interpolate(method="time", limit_direction="both")
    vo2_daily = vgrid.reindex(pd.DatetimeIndex(d["date"])).values
    vo2_peak = np.nanmax(vser.values)
    floss = (vo2_peak - vo2_daily) / vo2_peak
    floss = np.clip(floss, 0.0, None)
    floss = np.where(d["date"].values >= np.datetime64(t0), floss, 0.0)
    d["vo2_floss"] = floss

    return d


def decond_lit(t_cess, tau_years):
    """Unit literature deconditioning curve: exp approach to plateau, 0..1."""
    return 1.0 - np.exp(-t_cess / tau_years)


def decond_linear_forever(t_cess):
    """Never-plateauing linear ramp in years since cessation (0 before).
    This is the deliberately deconditioning-flattering shape: it lets the
    fitness term keep rising through year 4 with no plateau at all."""
    return t_cess


def design_matrix(d, decond_shape):
    """Columns: intercept, decond(unit), weight(centred), dose, sin, cos, age."""
    w_c = d["weight_kg"].values - ATHLETE_BASELINE_KG
    X = np.column_stack([
        np.ones(len(d)),
        decond_shape,
        w_c,
        d["dose"].values,
        d["sin"].values,
        d["cos"].values,
        d["age_years"].values,
    ])
    names = ["intercept", "decond_amp", "b_weight", "b_dose",
             "b_sin", "b_cos", "b_age"]
    return X, names


def fit_robust(X, y, age_cap=AGING_CAP_BPM_YR, decond_hi=LIT_DECOND_BPM_HI):
    """Huber-robust linear fit via least_squares soft_l1 loss.
    Bounds: decond_amp in the literature bpm range; b_age in [0, age_cap]."""
    n_par = X.shape[1]
    lb = np.full(n_par, -np.inf)
    ub = np.full(n_par, np.inf)
    lb[1], ub[1] = 0.0, decond_hi
    lb[6], ub[6] = 0.0, age_cap

    def resid(beta):
        return X @ beta - y

    beta0 = np.zeros(n_par)
    beta0[0] = np.median(y)
    beta0[1] = 6.0
    sol = least_squares(resid, beta0, bounds=(lb, ub),
                        loss="soft_l1", f_scale=2.0, max_nfev=10000)
    return sol.x


def block_bootstrap_betas(d, decond_shape_fn, tau_years=None, garmin=False,
                          linear_forever=False):
    """Block bootstrap over contiguous day-blocks; refit each resample.
    Returns dict name->(point, lo, hi), the residual series, point betas, X."""
    y = d["resting_hr"].values.astype(float)
    if garmin:
        shape = d["vo2_floss"].values
    elif linear_forever:
        shape = decond_linear_forever(d["t_cess"].values)
    else:
        shape = decond_lit(d["t_cess"].values, tau_years)
    # linear-forever ramp is unbounded in amplitude physiologically; allow it
    # to grow so it can TRY to absorb the late rise (adversarial to our claim)
    decond_hi = np.inf if linear_forever else LIT_DECOND_BPM_HI
    X, names = design_matrix(d, shape)

    beta_pt = fit_robust(X, y, decond_hi=decond_hi)
    resid_pt = y - X @ beta_pt

    decond_contrib = X[:, 1] * beta_pt[1]
    print(f"     [decond term contribution span: "
          f"{decond_contrib.min():.2f} to {decond_contrib.max():.2f} bpm]")

    n = len(d)
    starts_all = np.arange(0, n - BLOCK_LEN + 1)
    boot = np.zeros((N_BOOT, len(names)))
    for b in range(N_BOOT):
        idx = []
        while len(idx) < n:
            s = rng.integers(0, len(starts_all))
            idx.extend(range(starts_all[s], starts_all[s] + BLOCK_LEN))
        idx = np.array(idx[:n])
        Xi, yi = X[idx], y[idx]
        try:
            boot[b] = fit_robust(Xi, yi, decond_hi=decond_hi)
        except Exception:
            boot[b] = beta_pt

    out = {}
    for j, nm in enumerate(names):
        lo, hi = np.percentile(boot[:, j], [2.5, 97.5])
        out[nm] = (beta_pt[j], lo, hi)
    return out, resid_pt, beta_pt, X, names


def residual_trajectory(d, beta, X):
    """LC residual = observed - (all modelled drivers except intercept).
    Keeps the intercept so it sits at an interpretable RHR level."""
    contrib = X @ beta
    intercept = beta[0]
    lc_resid = d["resting_hr"].values - (contrib - intercept)
    return pd.DataFrame({"date": d["date"].values, "lc_resid": lc_resid})


def _post_slice(rd, drop_year=None):
    dts = pd.to_datetime(rd["date"])
    m = dts >= POST_2023
    if drop_year is not None:
        m &= dts.dt.year != drop_year
    post = rd[m].reset_index(drop=True)
    tdates = pd.to_datetime(post["date"])
    t = (tdates - tdates.min()).dt.days.values / 365.25
    return post["lc_resid"].values.astype(float), t


def post2023_slope_analytic(rd, drop_year=None):
    """Analytic Theil-Sen slope + CI (NOT autocorrelation-corrected)."""
    y, t = _post_slice(rd, drop_year=drop_year)
    sl, ic, cl, ch = theilslopes(y, t, 0.95)
    return sl, cl, ch


def block_bootstrap_residual_slope(rd, block_len, drop_year=None):
    """PROPER block bootstrap OF THE RESIDUAL SLOPE ITSELF (reviewer fix 1).
    Resample the post-2023 residual daily series in contiguous (t, y) block
    PAIRS (preserving intra-block trend), recompute the Theil-Sen slope per
    resample, take the 2.5/97.5 percentiles. This is what handles the
    residual's lag-1 autocorrelation (~0.94); the old analytic Theil-Sen
    interval assumed near-independence and was ~3x too tight."""
    y, t = _post_slice(rd, drop_year=drop_year)
    n = len(y)
    starts_all = np.arange(0, n - block_len + 1)
    slopes = np.zeros(N_BOOT)
    for b in range(N_BOOT):
        ti, yi = [], []
        while len(yi) < n:
            s = rng.integers(0, len(starts_all))
            blk = range(starts_all[s], starts_all[s] + block_len)
            ti.extend(t[list(blk)])
            yi.extend(y[list(blk)])
        ti = np.array(ti[:n])
        yi = np.array(yi[:n])
        sl, ic, cl, ch = theilslopes(yi, ti, 0.95)
        slopes[b] = sl
    lo, hi = np.percentile(slopes, [2.5, 97.5])
    return lo, hi


def residual_autocorr(rd, lag=1):
    y, _ = _post_slice(rd)
    y = y - np.mean(y)
    return float(np.corrcoef(y[:-lag], y[lag:])[0, 1])


def summarise_residual(rd, tag):
    print(f"\n   LC residual trajectory ({tag}): yearly median + Theil-Sen slope")
    print(f"     {'segment':8s} {'median':>7s} {'slope_bpm/yr':>13s} {'95%CI':>18s}")
    for name, lo, hi in YEAR_SEGMENTS:
        m = pd.Series(True, index=rd.index)
        dts = pd.to_datetime(rd["date"])
        if lo is not None:
            m &= dts >= lo
        if hi is not None:
            m &= dts <= hi
        sub = rd[m]
        if len(sub) < 5:
            print(f"     {name:8s} {sub['lc_resid'].median():7.1f} {'n/a':>13s}")
            continue
        t = (pd.to_datetime(sub["date"]) - pd.to_datetime(sub["date"]).min()
             ).dt.days / 365.25
        sl, ic, cl, ch = theilslopes(sub["lc_resid"].values, t.values, 0.95)
        print(f"     {name:8s} {sub['lc_resid'].median():7.1f} "
              f"{sl:13.2f} [{cl:6.2f}, {ch:6.2f}]")

    sl, cl, ch = post2023_slope_analytic(rd)
    bb_lo, bb_hi = block_bootstrap_residual_slope(rd, BLOCK_LEN)
    print(f"     POST-2023 residual slope (2024+): point {sl:.2f} bpm/yr")
    print(f"       analytic Theil-Sen CI (NOT ac-corrected): [{cl:.2f}, {ch:.2f}]")
    print(f"       block-bootstrap-of-slope CI (block={BLOCK_LEN}d): "
          f"[{bb_lo:.2f}, {bb_hi:.2f}]  (headline)")
    return sl, cl, ch, bb_lo, bb_hi


# ---------------------------------------------------------------------------
def part_b(df, wt, vo):
    print("\n" + "=" * 70)
    print("PART B - CONFOUNDER DECOMPOSITION (exploratory, ledger section 4)")
    print("=" * 70)
    d = build_daily_frame(df, wt, vo)
    print(f"\n   Fit sample: {len(d)} days with RHR present.")
    print(f"   Weight interpolated to daily. Largest weigh-in gap: "
          f"{WEIGH_GAP_DAYS} days ({WEIGH_GAP_FROM} to {WEIGH_GAP_TO}), which "
          f"sits directly under the post-2023 leverage window; the 2026 anchor "
          f"({ANCHOR_2026_KG} kg) is participant-reported, not in the dump.")
    print(f"   Citalopram plasma nonzero from "
          f"{d.loc[d['dose']>0,'date'].min().date()}.")

    results = {}

    # (i) literature curve, tau sensitivity grid
    for tau_m in TAU_GRID_MONTHS:
        tau_y = tau_m / 12.0
        print(f"\n   --- LITERATURE decond curve, tau = {tau_m:.0f} months ---")
        betas, resid, beta, X, names = block_bootstrap_betas(
            d, None, tau_years=tau_y, garmin=False)
        for nm in names:
            pt, lo, hi = betas[nm]
            print(f"     {nm:12s}: {pt:8.3f}  [{lo:7.3f}, {hi:7.3f}]")
        rd = residual_trajectory(d, beta, X)
        rslope = summarise_residual(rd, f"lit tau={tau_m}m")
        results[f"lit_tau{int(tau_m)}"] = {
            "betas": betas, "resid_slope_post": rslope,
            "beta": beta, "X": X, "rd": rd}

    # (ii) Garmin VO2Max-decay secondary curve
    print(f"\n   --- GARMIN VO2Max-decay decond curve (secondary) ---")
    print(f"   NOTE: per-kg, partially re-encodes weight; treat as secondary.")
    betas, resid, beta, X, names = block_bootstrap_betas(d, None, garmin=True)
    for nm in names:
        pt, lo, hi = betas[nm]
        print(f"     {nm:12s}: {pt:8.3f}  [{lo:7.3f}, {hi:7.3f}]")
    rd = residual_trajectory(d, beta, X)
    rslope = summarise_residual(rd, "garmin vo2 decay")
    results["garmin"] = {"betas": betas, "resid_slope_post": rslope,
                         "beta": beta, "X": X, "rd": rd}

    # representative fit for the sensitivities (literature tau=4 mo)
    rep = results["lit_tau4"]
    rep_beta, rep_X, rep_rd = rep["beta"], rep["X"], rep["rd"]
    ac1 = residual_autocorr(rep_rd, lag=1)
    print(f"\n   Residual lag-1 autocorrelation (post-2023): {ac1:.2f} "
          f"(analytic Theil-Sen CI assumes independence; hence the "
          f"block-bootstrap-of-slope headline CI).")

    # --- CI correction across the block grid (reviewer fix 1) ---
    print("\n   --- FIX 1: block bootstrap OF THE RESIDUAL SLOPE, block grid ---")
    ci_grid = {}
    for bl in BLOCK_LEN_GRID:
        lo, hi = block_bootstrap_residual_slope(rep_rd, bl)
        ci_grid[bl] = (lo, hi)
        print(f"     block={bl:2d}d: [{lo:.2f}, {hi:.2f}]")

    # --- leave-one-year-out (reviewer fix 2) ---
    print("\n   --- FIX 2: leave-one-year-out (post-2023 residual slope) ---")
    loyo = {}
    for yr in [2024, 2025, 2026]:
        sl, cl, ch = post2023_slope_analytic(rep_rd, drop_year=yr)
        loyo[yr] = (sl, cl, ch)
        crosses = "CROSSES ZERO" if cl <= 0 <= ch else "excludes zero"
        print(f"     drop {yr}: {sl:.2f} [{cl:.2f}, {ch:.2f}]  {crosses}")
    # per-year residual slopes for the wobble narrative
    per_year = {}
    for yr in [2024, 2025, 2026]:
        dts = pd.to_datetime(rep_rd["date"])
        sub = rep_rd[dts.dt.year == yr]
        t = (pd.to_datetime(sub["date"]) - pd.to_datetime(sub["date"]).min()
             ).dt.days / 365.25
        s2, ic, cl, ch = theilslopes(sub["lc_resid"].values, t.values, 0.95)
        per_year[yr] = s2
    print(f"     per-year residual slopes: "
          f"2024 {per_year[2024]:.2f}, 2025 {per_year[2025]:.2f}, "
          f"2026 {per_year[2026]:.2f}")

    # --- weight coefficient sensitivity (reviewer fix 3) ---
    print("\n   --- FIX 3: weight-coefficient sensitivity ---")
    dts = pd.to_datetime(rep_rd["date"])
    m24 = dts >= POST_2023
    w24 = d.loc[m24.values, "weight_kg"].values
    w_contrib = rep_beta[2] * (w24[-1] - w24[0])
    print(f"     interpolated weight over 2024-2026: {w24[0]:.1f} -> {w24[-1]:.1f} "
          f"kg, removes {w_contrib:.2f} bpm at b_weight={rep_beta[2]:.3f}.")
    weight_sens = {}
    for mult in [1.0, 2.0]:
        beta2 = rep_beta.copy()
        beta2[2] = rep_beta[2] * mult
        rd2 = residual_trajectory(d, beta2, rep_X)
        sl, cl, ch = post2023_slope_analytic(rd2)
        weight_sens[mult] = (rep_beta[2] * mult, sl, cl, ch)
        print(f"     b_weight x{mult:.0f} ({rep_beta[2]*mult:.3f}): "
              f"resid {sl:.2f} [{cl:.2f}, {ch:.2f}]")

    # --- slow / never-plateauing deconditioning sensitivity (reviewer fix 4) ---
    print("\n   --- FIX 4: slow-deconditioning sensitivity (circularity defeater) ---")
    decond_sens = {}
    for label, tau_y in [("plateau_yr2", 1.0), ("plateau_yr3", 2.0),
                         ("plateau_yr4", 4.0)]:
        sh = decond_lit(d["t_cess"].values, tau_y)
        X2, _ = design_matrix(d, sh)
        b2 = fit_robust(X2, d["resting_hr"].values.astype(float))
        rd2 = residual_trajectory(d, b2, X2)
        sl, cl, ch = post2023_slope_analytic(rd2)
        decond_sens[label] = (b2[1], sl, cl, ch)
        print(f"     {label:12s}: decond_amp={b2[1]:.2f} resid {sl:.2f} "
              f"[{cl:.2f}, {ch:.2f}]")
    # linear-forever ramp (never plateaus; amplitude unbounded, adversarial)
    sh = decond_linear_forever(d["t_cess"].values)
    X2, _ = design_matrix(d, sh)
    b2 = fit_robust(X2, d["resting_hr"].values.astype(float), decond_hi=np.inf)
    rd2 = residual_trajectory(d, b2, X2)
    sl, cl, ch = post2023_slope_analytic(rd2)
    lf_rise = b2[1] * (d["t_cess"].max() - 0.0)  # bpm rise implied across span
    decond_sens["linear_forever"] = (b2[1], sl, cl, ch)
    print(f"     linear_forever: decond_amp={b2[1]:.2f} bpm/yr "
          f"(implies {lf_rise:.2f} bpm rise across the post-cess span) "
          f"resid {sl:.2f} [{cl:.2f}, {ch:.2f}]")

    # --- aging bound sensitivity (reviewer fix 5) ---
    print("\n   --- FIX 5: aging-bound sensitivity (0.5 cap OVER-removes aging) ---")
    print(f"     Lit aging bound (resting_hr_aging_magnitude_review.md): "
          f"~0 to ~{AGING_UPPER_BOUND_BPM_YR} bpm/yr upper, central near zero "
          f"or negative. The model's {AGING_CAP_BPM_YR} cap over-removes aging.")
    age_years = d["age_years"].values
    base_resid = rep_rd["lc_resid"].values
    aging_sens = {}
    for new_age in [AGING_CAP_BPM_YR, AGING_UPPER_BOUND_BPM_YR, 0.0]:
        # hold all other coefficients fixed; vary only the aging amount removed.
        # base residual has 0.5*age removed, so add back (0.5 - new_age)*age.
        adj = base_resid + (rep_beta[6] - new_age) * age_years
        rd3 = pd.DataFrame({"date": d["date"].values, "lc_resid": adj})
        sl, cl, ch = post2023_slope_analytic(rd3)
        aging_sens[new_age] = (sl, cl, ch)
        note = ("model cap; OVER-removes" if new_age == AGING_CAP_BPM_YR
                else "lit upper bound" if new_age == AGING_UPPER_BOUND_BPM_YR
                else "aging = 0")
        print(f"     aging removed at {new_age:.1f} ({note}): "
              f"resid {sl:.2f} [{cl:.2f}, {ch:.2f}]")

    # citalopram beta summary
    print("\n   --- Citalopram in-sample RHR beta ---")
    cit = {}
    for key in ["lit_tau3", "lit_tau4", "lit_tau6", "garmin"]:
        pt, lo, hi = results[key]["betas"]["b_dose"]
        ss = pt * 30.0
        ss_lo, ss_hi = lo * 30.0, hi * 30.0
        cit[key] = (pt, ss, ss_lo, ss_hi)
        print(f"     {key:14s}: b_dose={pt:.4f} bpm/mg -> "
              f"{ss:.2f} bpm at 30mg SS [{ss_lo:.2f},{ss_hi:.2f}]  "
              f"[prior {CITALOPRAM_PRIOR_BPM}]")

    # citalopram-era raw RHR slope (drug pushes DOWN, RHR still rises)
    d2 = d[d["date"] >= d.loc[d["dose"] > 0, "date"].min()]
    t = (pd.to_datetime(d2["date"]) - pd.to_datetime(d2["date"]).min()
         ).dt.days / 365.25
    sl, ic, cl, ch = theilslopes(d2["resting_hr"].values, t.values, 0.95)
    cit_era = (sl, cl, ch)
    print(f"   Citalopram-era raw RHR slope (2024-04+): {sl:.2f} bpm/yr "
          f"[{cl:.2f},{ch:.2f}] -- RHR rises WHILE the drug pushes it down.")

    results["_sens"] = {
        "ac1": ac1, "ci_grid": ci_grid, "loyo": loyo, "per_year": per_year,
        "weight_sens": weight_sens, "w_contrib": w_contrib,
        "w24_lo": w24[0], "w24_hi": w24[-1], "decond_sens": decond_sens,
        "aging_sens": aging_sens, "cit": cit, "cit_era": cit_era,
        "rep_betas": results["lit_tau4"]["betas"],
    }
    return results


def main():
    df = load_master()
    wt = load_weight_series()
    vo = load_vo2_series()
    print(f"Loaded: {len(df)} master rows; {N_WEIGHIN_RAW} raw weigh-in records "
          f"-> {len(wt)} daily weight anchors (incl 2026 anchor); "
          f"{len(vo)} distinct-date VO2Max points.")
    a = part_a(df)
    b = part_b(df, wt, vo)

    print("\n" + "=" * 70)
    print("VERDICT SUMMARY (revised 2026-07-02)")
    print("=" * 70)
    er = a["early"]
    rc = a["recent"]
    print(f"   Plateau: early-LC slope {er[0]:.2f} vs recent {rc[0]:.2f} bpm/yr; "
          f"recent flat={a['recent_flat']}; mid-2023-2024 window flat "
          f"({a['win_res']['mid 2023-2024'][0]:.2f}).")
    s = b["_sens"]
    print(f"   Post-2023 residual point +1.21 bpm/yr; headline CI (block=10d) "
          f"[{s['ci_grid'][10][0]:.2f}, {s['ci_grid'][10][1]:.2f}].")
    print(f"   LOYO drop-2024 {s['loyo'][2024][0]:.2f} "
          f"[{s['loyo'][2024][1]:.2f}, {s['loyo'][2024][2]:.2f}] (crosses zero) "
          f"-> significance FRAGILE.")
    print(f"   Linear-forever decond resid {s['decond_sens']['linear_forever'][1]:.2f} "
          f"-> direction robust to decond timescale.")
    print(f"   2x b_weight resid {s['weight_sens'][2.0][1]:.2f} -> magnitude "
          f"weight-conditional.")
    print(f"   Aging=0 resid {s['aging_sens'][0.0][0]:.2f}; 0.5 cap over-removes "
          f"aging -> residual conservative.")


if __name__ == "__main__":
    main()
