"""Pull the actual clauses behind the striking findings in
categories-analysis.md. Sanity-checks: are the patterns real human
stories or substring-match artifacts? Also surfaces dictionary gaps
(esp. the empty symptoom_emotioneel category).
"""
from __future__ import annotations

import csv
import json
import re
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).resolve().parent
CLAUSE_CSV = HERE / "notes-categorized-clauses.csv"
DAY_CSV = HERE / "notes-categorized.csv"
NOTES_JSON = HERE.parent / "01-language-around-crashes" / "day_entries_with_notes.json"
OUT_MD = HERE / "verification.md"

ERA_SPLIT = date(2023, 12, 31)


def load_clauses():
    rows = []
    with CLAUSE_CSV.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            r["categories_list"] = r["categories"].split("|") if r["categories"] else []
            r["date"] = date.fromisoformat(r["date"])
            rows.append(r)
    return rows


def load_day_meta():
    """Returns {date: {score, in_crash, is_leadup, era, categories}}."""
    out = {}
    with DAY_CSV.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            d = date.fromisoformat(r["date"])
            out[d] = {
                "score": r["score"],
                "in_crash": r["in_crash_episode"] == "True",
                "is_leadup": r["is_leadup"] == "True",
                "era": r["era"],
                "categories": set(r["categories"].split("|")) if r["categories"] else set(),
            }
    return out


def load_full_notes():
    entries = json.loads(NOTES_JSON.read_text(encoding="utf-8"))
    return {date.fromisoformat(e["date"]): e["note"].strip() for e in entries if e.get("note") and e["note"].strip()}


def section(md, title):
    md.append("")
    md.append(f"## {title}")
    md.append("")


def show_clauses(md, clauses, max_n=None):
    if not clauses:
        md.append("_(no matching clauses)_")
        return
    shown = clauses[:max_n] if max_n else clauses
    for c in shown:
        cats = ", ".join(c["categories_list"]) if c["categories_list"] else "_(none)_"
        md.append(f"- **{c['date'].isoformat()}** ({cats}): \"{c['clause']}\"")
    if max_n and len(clauses) > max_n:
        md.append(f"")
        md.append(f"_...{len(clauses) - max_n} more_")


def main():
    clauses = load_clauses()
    day_meta = load_day_meta()
    full_notes = load_full_notes()

    md = ["# Verification — actual clauses behind the striking findings", ""]
    md.append("Each section pulls the real clauses behind a category-analysis row, so we can:")
    md.append("- Confirm patterns are real, not substring-match artifacts.")
    md.append("- Surface dictionary gaps (clauses that *should* have matched but didn't).")
    md.append("- Read the human story behind the numbers.")
    md.append("")
    md.append("Generated by [verify_findings.py](verify_findings.py).")

    # ─── Finding 1: triggers_extern, 8.7x on crash days ───
    section(md, "Finding 1 — triggers_extern (8.7x on crash days)")
    md.append("Clauses where `triggers_extern` fired on a crash day. Confirms whether external illness")
    md.append("(corona / griep / verkoudheid) is a real precipitant subtype.")
    md.append("")
    triggers_on_crash = [c for c in clauses
                         if "triggers_extern" in c["categories_list"]
                         and day_meta.get(c["date"], {}).get("in_crash")]
    show_clauses(md, triggers_on_crash)
    md.append("")
    md.append(f"_n = {len(triggers_on_crash)} clauses across {len({c['date'] for c in triggers_on_crash})} distinct days._")

    # ─── Finding 2: belasting_gezin late crash days (0% → 22%) ───
    section(md, "Finding 2 — belasting_gezin on LATE-era crash days (0% → 22%)")
    md.append("The most striking era shift in crash language. Are these real caregiving moments")
    md.append("during crashes, or are family names appearing in mundane context?")
    md.append("")
    late_crash_gezin = [c for c in clauses
                        if "belasting_gezin" in c["categories_list"]
                        and day_meta.get(c["date"], {}).get("in_crash")
                        and c["date"] > ERA_SPLIT]
    show_clauses(md, late_crash_gezin)
    md.append("")
    md.append(f"_n = {len(late_crash_gezin)} clauses across {len({c['date'] for c in late_crash_gezin})} distinct days._")

    # ─── Finding 3: belasting_cognitief in LATE lead-up days (0% → 12%) ───
    section(md, "Finding 3 — belasting_cognitief on LATE-era LEAD-UP days (0% → 12%)")
    md.append("This is the most surprising finding: cognitive load appears in lead-up language only in the late era.")
    md.append("Verifying whether this is real work-context preceding crashes, or substring false-positives.")
    md.append("")
    late_leadup_cog = [c for c in clauses
                       if "belasting_cognitief" in c["categories_list"]
                       and day_meta.get(c["date"], {}).get("is_leadup")
                       and c["date"] > ERA_SPLIT]
    show_clauses(md, late_leadup_cog)
    md.append("")
    md.append(f"_n = {len(late_leadup_cog)} clauses across {len({c['date'] for c in late_leadup_cog})} distinct days._")

    # For each unique date, show the surrounding full note for context
    md.append("### Full notes for those dates (for context)")
    md.append("")
    for d in sorted({c["date"] for c in late_leadup_cog}):
        meta = day_meta.get(d, {})
        full = full_notes.get(d, "")
        md.append(f"- **{d.isoformat()}** (score {meta.get('score', '?')}): {full}")

    # ─── Finding 4: symptoom_emotioneel is 0% everywhere ───
    section(md, "Finding 4 — symptoom_emotioneel is 0% everywhere (dictionary gap?)")
    md.append("The category had 13 phrases but never matched a single clause. Spot-check by looking for")
    md.append("possibly-emotional-symptom clauses on crash days that fell through to other categories or context_neutraal.")
    md.append("")
    # Look for crash-day clauses with emotional-flavor words NOT in the dictionary
    candidate_words = ["verdriet", "verdrietig", "boos", "kortaf", "geirriteerd", "geïrriteerd",
                       "moedeloos", "machteloos", "weinig zin", "geen zin", "leeg gevoel",
                       "geraakt", "kwetsbaar", "bang", "onrustig"]
    candidates = []
    for c in clauses:
        if not day_meta.get(c["date"], {}).get("in_crash"):
            continue
        text = c["clause"].lower()
        for word in candidate_words:
            if word in text:
                candidates.append((word, c))
                break
    if candidates:
        md.append(f"Crash-day clauses containing possibly-emotional-symptom vocabulary NOT currently in the dictionary:")
        md.append("")
        for word, c in candidates:
            cats = ", ".join(c["categories_list"]) if c["categories_list"] else "_(none)_"
            md.append(f"- **{c['date'].isoformat()}** matched on \"{word}\", current cats: {cats}")
            md.append(f"  Clause: \"{c['clause']}\"")
    else:
        md.append("_No candidates found in crash-day clauses. The category may genuinely be absent from this user's vocabulary, OR the candidate-word list above is missing the user's actual phrasing._")
    md.append("")
    md.append("**Action item**: If the user does experience emotional symptoms but expresses them in words not on the dictionary OR the candidate list above, we need to extend the dictionary.")

    # ─── Finding 5: context_neutraal is 80% on lead-up days ───
    section(md, "Finding 5 — context_neutraal is 80% on lead-up days")
    md.append("Are these mundane day-shape clauses, or are we missing categories that should catch them?")
    md.append("Sampling 20 lead-up clauses that fell to context_neutraal only.")
    md.append("")
    neutral_only_leadup = [c for c in clauses
                           if c["categories_list"] == ["context_neutraal"]
                           and day_meta.get(c["date"], {}).get("is_leadup")]
    show_clauses(md, neutral_only_leadup, max_n=20)
    md.append("")
    md.append(f"_n = {len(neutral_only_leadup)} total neutral-only lead-up clauses._")
    md.append("")
    md.append("**Read these critically**: any of them are actually saying something category-worthy that the dictionary missed?")

    # ─── Finding 6: crash-day signature — sample to confirm symptom-heavy nature ───
    section(md, "Finding 6 — crash days are 92% symptoom_fysiek (sample to confirm)")
    md.append("Show 15 random crash-day clauses tagged with `symptoom_fysiek` to confirm the dominant category fires for the right reasons.")
    md.append("")
    fysiek_crash = [c for c in clauses
                    if "symptoom_fysiek" in c["categories_list"]
                    and day_meta.get(c["date"], {}).get("in_crash")]
    # Show 15 spread across time
    if len(fysiek_crash) > 15:
        step = len(fysiek_crash) // 15
        sample = fysiek_crash[::step][:15]
    else:
        sample = fysiek_crash
    show_clauses(md, sample)
    md.append("")
    md.append(f"_n = {len(fysiek_crash)} total clauses; {len(sample)} sampled across the timeline._")

    OUT_MD.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
